Repository arduino-libraries/Arduino_POSIXStorage, pull requests merged in 2024-03, with the labels that each got.

#18 Fix regression re report-size-deltas after updating actions/upload-artifact.
  .github/workflows/compile-examples.yml
  .github/workflows/report-size-deltas.yml
Labels: type: imperfection, topic: infrastructure

#13 [AE-181] Add check-release-version.yml workflow
  .github/workflows/check-release-version.yml
Labels: type: enhancement, topic: infrastructure

#21 Fix bug that breaks RS485 on the Opta
  src/Arduino_POSIXStorage.cpp
Labels: type: imperfection, topic: code
